/*
  NAME:
    rdtables.c

  AUTHOR:
    Tomas E. Tecce
    Centro de Astro-Ingenieria (AIUC)
    Pontificia Universidad Catolica de Chile
    Av. Vicuna Mackenna 4860, 7820436 Macul, Santiago, Chile
    E-mail: ttecce@astro.puc.cl

  PURPOSE:
    Generate tables of values of disc scale length for use in SA galaxy
    formation models.

  MAJOR TOPICS:
    Galaxy formation; disc formation; semi-analytic methods

  CALLING SEQUENCE:
    ./rdtables parameterfile 

  NOTES:
    Tables are generated for selected values of redshift, halo
    concentration c_200 (for a NFW profile model), and bulge mass fraction
    mb=Mbulge/M_200. Two different types of files are generated:
    rdtable_NNN_NNN stores values of disc scale length and vctable_NNN_NNN 
    stores the value of the circular velocity at the radius that encloses 
    a given percentage of the total baryonic mass (specified in the 
    parameters file).

    The tables are designed to be independent of the cosmological model, 
    and the values in the tables use the following units: unit of length is
    (virial mass/critical density)^1/3, unit of velocity is the virial 
    velocity. 
  
    Each table file is a collection of double-entry data tables for a given
    redshift and halo concentration: table(i,j) is the value corresponding
    to row i in disc mass fraction md=Mdisc/M_200 and column j in halo spin
    parameter. The first line in each file lists the current redshift and 
    concentration. Nbulge tables follow; for easier reading, each one is 
    headed by a line with just the corresponding value of mb. An additional
    file, tables_header.dat, lists all the redshift, concentration, m_d,
    m_b and lambda values used.

    Compilation options (enable in Makefile):
    - TESTMODE runs a single calculation in interactive mode, then
      exits. Useful to evaluate performance of the program. 
    - DEBUG prints extra information.
      
  COMPATIBILITY:
    Tested with gcc version 4.2.4

  DEPENDENCES:
    If compiled with TESTMODE, requires the tables of concentration vs mass
    M_200 generated by the conctables program.

  MODIFICATION HISTORY:
    - 2011-06-30: Revised and debugged test mode. Added extra parameters to
      enable selection of which table set is to be generated.
    - 2010-12-29: Removed option MassFractionForVc; use of total baryonic
      mass results in Vc=0 whenever the bulge alone is equal to or greater
      than the selected fraction. Changed to return the velocity at a given
      multiple of the scale radius. TET
    - 2010-12-15: Changed the system of units in rditer.c and the output to
      produce cosmology-independent tables. Removed tables of optical 
      radius. TET
    - 2010-11-22: Major revision of the code to use the tables of
      concentration vs halo mass generated with the latest versions of
      J. Bullock's CVIR code. Also the tables are for ranges in halo
      concentration instead of virial mass, as before, to make the tables
      less dependent on a particular cosmological model. The format of the 
      tables is also modified. Command line parameters have been dropped for
      the time being. TET
    - 2010 January: Modified to take parameters from the command line (this
      allows the simultaneous calculation of tables in a parallel
      environment). TET
    - Created 2009, TET
*/
#include "allvars.h"
#include "proto.h"
#include "readparameters.h"


int main(int argc, char **argv)
{
  int i, j;
  int status;
  time_t t1, t2, currtime;
  struct tm *loctime;
  char rdoutput_fname[FILENAME_MAX], vcoutput_fname[FILENAME_MAX];
  char hostname[256];
   double cmin, cmax, cbinwidth;

  
  (void)time(&t1);
  printf("\n"
	 "#######\n"
	 "# rdtables\n"
	 "#######\n\n");

  if (argc < 2) {
    fprintf(stderr, "Error: no parameter file given - Exit\n"); 
    fflush(stderr);
    exit(EXIT_FAILURE);
  }

  mygethostname(hostname, 256);
  currtime = time(NULL);
  loctime = localtime(&currtime);
  printf("Running on %s - Run started %s\n", hostname, asctime(loctime)); 
  fflush(stdout);
  
  readparameterfile(*(argv+1));

  allocate_arrays();
  Count_div = 0;
  Count_itmax = 0;

  /* Determine output times for rscale tables, and values for the
     table rows and columns */
  output_times(); 
  determine_axes_values();
  printf("\n");

  /* Calculation of the abscissas and weights of the 
     Gauss-Laguerre integration formula */
  dgaulag(Xgl, Wgl, NPOINTSGL, 2);
#ifdef DEBUG
  printf("Gauss-Laguerre points and weights:\n");
  for (i=1; i<=NPOINTSGL; i++)
    printf("%g ", Xgl[i]);
  printf("\n");
  for (i=1; i<=NPOINTSGL; i++)
    printf("%g ", Wgl[i]);
  printf("\n\n");
#endif

  /* Load tables of concentration vs mass into memory */
  /* In test mode, loads a set of concentration vs m200 tables for a 
     given cosmology. Else, load a table with a list of redshifts and
     the corresponding maximum and minimum concentrations */
#ifndef TESTMODE
  sprintf(NameConcentrationTables, "cranges.dat");
#endif
  load_concentration_tables(NameConcentrationTables);

  
  for (i=0; i<NumOutputTimes; i++) {
    
    /* Find the range of valid concentration values for this redshift,
       and divide it in the selected number of bins */
    /* 
     * The range of concentration values spanned by haloes in a fixed mass
     * range changes with redshift. This means that if we use a fixed
     * number of concentration bins and a fixed concentration range, for
     * early times we will have much fewer points (to interpolate mass as a
     * function of concentration) than at lower redshift. The solution I
     * propose is to take the range of c200 values at each redshift and
     * then divide it in a fixed number of bins. 
     * TOMAS 2010-11-26 
     */
    /* 2010-12-15 The range of concentration values will depend on 
       cosmology (through the tables) - the range should be wide enough
       to cover the full spectrum of cosmologies that may be considered */
    /* Range of tables is read from file cranges.dat */
    concentration_range(ZZ[i], &cmin, &cmax);
    cbinwidth = (cmax-cmin)/((double)NumCbins);
    Conc_rscale[0] = cmin;
    for (j=1; j<NumCbins; j++)
      Conc_rscale[j] = Conc_rscale[j-1]+cbinwidth;
    printf("Concentration range: [%g - %g]\n\n", Conc_rscale[0], 
	   Conc_rscale[NumCbins-1]);

#ifdef DEBUG
    printf("\nConcentrations:\n");
    for (j=0; j<NumCbins; j++) {
      printf("  %.6f\n", Conc_rscale[j]);
    }
    printf("\n");
#endif

#ifdef TESTMODE
    /* If test mode is enabled at compilation, run a single calculation
       asking the user for input, then exit */
    test_mode();
#endif

    for (j=0; j<NumCbins; j++) {
      printf("Generating disc scale length table for z = %8.6f, "
	     "c200 = %5.2f\n", ZZ[i], Conc_rscale[j]);

      /* Only generate tables if the mean concentration in the selected bin
	 is within the valid range of concentrations for this redshift. */
      if (Conc_rscale[j] >= cmin && Conc_rscale[j] < cmax) {
  
	sprintf(rdoutput_fname, "%s/rdtable_%03d_%03d", Path1, i, j);
	sprintf(vcoutput_fname, "%s/vctable_%03d_%03d", Path1, i, j);

	printf("    Storing data in files: ");
	if (RdTablesOn != 0) 
	  printf("%s\n", rdoutput_fname);
	if (VcTablesOn != 0) {
	  if (RdTablesOn != 0)
	    printf("                           %s\n", vcoutput_fname);
	  else
	    printf("%s\n", vcoutput_fname);
	}
	status = generate_rscale_table(i, Conc_rscale[j], rdoutput_fname,
				       vcoutput_fname);
	if (status < 0) {
	  fprintf(stderr, "Error (main): function generate_rscale_table "
		  "returned an error code - Exit\n"); fflush(stderr);
	  exit(EXIT_FAILURE);
	}
      }
      else {
	printf("    Concentration out of range for this redshift "
	       "[%.2f - %.2f]\n", cmin, cmax);
      }
      printf("\n");
    }
    printf("\n");
  }

  free_arrays();
  free_concentration_tables();

  printf("Found %d divergences and %d max iterations\n", Count_div,
	 Count_itmax); fflush(stdout);

  (void)time(&t2);
  printf("\nTime taken: %d sec\n", (int)(t2-t1)); fflush(stdout);
  return EXIT_SUCCESS;
}
